# Generated by Django 4.2.30 on 2026-07-02 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('sedacion', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('consciente', 'Consciente'), ('profunda', 'Profunda'), ('naap', 'NAAP / propofol')], max_length=20)),
                ('farmacos', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tiempo_retiro_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('intubacion_cecal', models.BooleanField(blank=True, null=True)),
                ('foto_doc_ciego', models.BooleanField(blank=True, null=True)),
                ('ileoscopia_distal', models.BooleanField(blank=True, null=True)),
                ('boston_cd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('boston_ct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('boston_ci', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('insp_pasiva', models.CharField(blank=True, max_length=300)),
                ('insp_activa', models.CharField(blank=True, max_length=300)),
                ('tacto_rectal', models.CharField(blank=True, max_length=300)),
                ('canal_anal', models.CharField(blank=True, max_length=300)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_creados', to=settings.AUTH_USER_MODEL)),
                ('enfermera', models.ForeignKey(blank=True, limit_choices_to={'rol': 'enfermera'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_como_enfermera', to='personal.personal')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'medico'}, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_como_medico', to='personal.personal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaColonoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('colonoscopia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='colonoscopia.colonoscopia')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoColonoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('colonoscopia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='colonoscopia.colonoscopia')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiopsiaColonoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frasco', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('n_lesiones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('colonoscopia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biopsias', to='colonoscopia.colonoscopia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentoColon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('ciego', 'Ciego'), ('ascendente', 'Colon ascendente'), ('transverso', 'Colon transverso'), ('descendente', 'Colon descendente'), ('sigmoides', 'Colon sigmoides'), ('recto', 'Recto')], max_length=20)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('alterado', 'Alterado')], default='normal', max_length=10)),
                ('texto', models.TextField(blank=True)),
                ('colonoscopia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='colonoscopia.colonoscopia')),
            ],
            options={
                'ordering': ['colonoscopia_id', 'id'],
                'unique_together': {('colonoscopia', 'segmento')},
            },
        ),
    ]
