# Generated by Django 4.2.30 on 2026-07-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenEndoscopica',
        ),
    ]
