# Generated by Django 4.2.30 on 2026-07-02 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('sedacion', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('consciente', 'Consciente'), ('profunda', 'Profunda'), ('naap', 'NAAP / propofol')], max_length=20)),
                ('farmacos', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tiempo_examen_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peace_esofago', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('peace_estomago', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('peace_duodeno', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_creados', to=settings.AUTH_USER_MODEL)),
                ('enfermera', models.ForeignKey(blank=True, limit_choices_to={'rol': 'enfermera'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_como_enfermera', to='personal.personal')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'medico'}, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_como_medico', to='personal.personal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaEDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='eda.eda')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoEDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='eda.eda')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiopsiaEDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frasco', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('n_lesiones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biopsias', to='eda.eda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentoEDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('esofago', 'Esófago'), ('fondo', 'Estómago — Fondo'), ('cuerpo', 'Estómago — Cuerpo'), ('angulo', 'Estómago — Ángulo'), ('antro', 'Estómago — Antro'), ('bulbo', 'Duodeno — Bulbo'), ('segporcion', 'Duodeno — 2.ª porción')], max_length=20)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('alterado', 'Alterado')], default='normal', max_length=10)),
                ('texto', models.TextField(blank=True)),
                ('cardias_hill', models.CharField(blank=True, choices=[('hill1', 'Hill I'), ('hill2', 'Hill II'), ('hill3', 'Hill III'), ('hill4', 'Hill IV')], max_length=10)),
                ('piloro', models.CharField(blank=True, choices=[('centrico', 'Céntrico y permeable'), ('deformado', 'Deformado'), ('estenotico', 'Estenótico')], max_length=15)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='eda.eda')),
            ],
            options={
                'ordering': ['eda_id', 'id'],
                'unique_together': {('eda', 'segmento')},
            },
        ),
    ]
