# Generated by Django 4.2.30 on 2026-07-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('medico', 'Médico endoscopista'), ('enfermera', 'Enfermera asistente')], max_length=20)),
                ('colegiatura', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
    ]
