# Generated by Django 4.2.30 on 2026-07-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEndoscopica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('archivo', models.ImageField(upload_to='endoscopia/%Y/%m/')),
                ('epigrafe', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('eda', 'colonoscopia')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['content_type', 'object_id', 'orden'],
            },
        ),
    ]
